/* TABLA USUARIOS */
CREATE TABLE users(
	id_user INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
    email VARCHAR(80) NOT NULL, 
    pass VARCHAR(255) NOT NULL
);

/* TABLA PROVEEDORES */
CREATE TABLE suppliers(
	id_supplier INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    company_name VARCHAR(100) NOT NULL,
    contact_person VARCHAR(70) NOT NULL, 
    email VARCHAR(80) NOT NULL, 
    id_type INT NOT NULL,
    NIT VARCHAR(20) NOT NULL, 
    phone VARCHAR(10) NOT NULL, 
    city VARCHAR(60) NOT NULL,
    created_at DATE NOT NULL DEFAULT (CURRENT_DATE),
    
    FOREIGN KEY (id_type) REFERENCES suppliers_type(id_type)
);

/* TABLA TIPOS DE PROVEEDORES */
CREATE TABLE suppliers_type(
	id_type INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    supplier_type VARCHAR(100) NOT NULL
);

/* YA QUE LA CONTRASEÑA SE ENCUENTRA HASHEADA, ES NECESARIO CREAR EL USUARIO CON EL SIGUIENTE QUERY */
INSERT INTO users(email, pass) VALUES ('admin@kratt.com','$2b$05$XBhkBcU9/5IBo33pW79WPuwGUsIUQD3o2yH4CrOC3fDaD1a/KsbU6'); 

/* USUARIO ORIGINAL SIN CONTRASEÑA HASHEADA */
INSERT INTO users(email, pass) VALUES ('admin@kratt.com','admin2025'); 
